### ISSUE TITLE
Privacy Manifest file addition if needed

### ISSUE THREAD

**Issue by slice-varundudeja** [100mslive/100ms-ios-sdk#122]
There's new requirement from apple to add privacy manifest in case of usage of privacy apis listed here
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

can you check this and create a release if this is the case?

**Comment by gzerad** [comment]
Hi thank you for reporting.  We are working on including this in next SDK release.

**Comment by gzerad** [comment]
Manifest has been added in 1.9.0 release
