### ISSUE TITLE
Support for screen sharing

### ISSUE THREAD

**Issue by niralishaha25** [100mslive/100ms-ios-sdk#17]
Looking for support for screen sharing but can't get relevant information in the documentation / pod / example

**Comment by ygit** [comment]
@niralishaha25 It's a work in progress on iOS. It's available on Android as a beta at the moment.
https://docs.100ms.live/android/v2/features/Screen-Share

**Comment by niralishaha25** [comment]
Thanks for quick reply. My team has recently implemented screen share on android, but now we are eagerly looking for iOS implementation. 
Can you let me know approximate release timeline?

**Comment by gzerad** [comment]
We dont have an ETA yet, but I would not expect it sooner than mid December.

**Comment by gzerad** [comment]
@niralishaha25 not sure if you are still waiting but we have released the screen share feature today. Checkout the docs [here](https://www.100ms.live/docs/ios/v2/features/screen-share) on how to integrate.
