### ISSUE TITLE
Set local user mute on join

### ISSUE THREAD

**Issue by BhavinBhadani** [100mslive/100ms-ios-sdk#21]
How to set audio and video track mute on join by default? 

I tried this code but it doesnt work

        hmsSDK.join(config: config, delegate: self)
        hmsSDK.localPeer?.localAudioTrack()?.setMute(true)
        hmsSDK.localPeer?.localVideoTrack()?.setMute(true)

**Comment by gzerad** [comment]
You need to listen to 
on(track: HMSTrack, update: HMSTrackUpdate, for peer: HMSPeer)
callback where update is `trackAdded` and `peer.isLocal == true` and setMute for each track there

**Comment by BhavinBhadani** [comment]
@gzerad Thanks. It works :)
