### ISSUE TITLE
Way to sort active speakers runtime

### ISSUE THREAD

**Issue by StackHelp** [100mslive/100ms-ios-sdk#22]
Is there any way we can put active speakers above other speakers when we got speakers like in `HMSDataSourceDelegate`?

For e.g. we have this kind of model where we have a local user and 5 other remote users `["local user", "a", "b", "c", "d", "e"]` and when we have active speaker list i.e. ["e", "d"], I want them to move after "local user" like  `["local user", "d", "e" "a", "b", "c"]`. I know we have to do some sorting kind of stuff but we already have a sort descriptor which is called when update model and not for speakers, and by sorting in the speaker list, isn't it affect Datasource frequently? Any other idea?

**Comment by gzerad** [comment]
You can use single sort descriptor to do sorting by multiple criteria. I.e

```
dataSource.sortComparator = { lhs, rhs in
   //sort by local peer first
   if lhs.peer.isLocal != rhs.peer.isLocal {
      return  lhs.peer.isLocal 
   }
   //sort by active speaker
   lhsIndex = activeSpeakers.firstIndex(of: lhs)
   rhsIndex = activeSpeakers.firstIndex(of: rhs)
   return lhsIndex < rhsIndex
}
```

Then in the didUpdate(speakers:) callback of the data source update the activeSpeakers and call reload() on the data source.

Having said that you are actually right in your assumption that the updates would be too frequent but concern is not performance but that UI will be too disorienting with constant reordering. To combat that a more clever sorting is required such that if all speakers are on screen just highlighting the active one with the border is better UX. If some speaker that is not on the screen has become active it should replace the least active speaker that is currently on the screen. Hope this helps.

**Comment by StackHelp** [comment]
Right. By performance, I mean the same that UI may flicker and that's not a good for the experience. However, the last suggestion is what I am trying to do right now.

**Comment by StackHelp** [comment]
@gzerad I put the above code in `didUpdate(_ speakers: [HMSViewModel])` however it doesn't work.

**Comment by gzerad** [comment]
Can you share the didUpdate implementation?

**Comment by StackHelp** [comment]
Yes

      func didUpdate(_ speakers: [HMSViewModel]) {
         defer {
               self.speakers = speakers
         }
              dataSource.sortComparator = { lhs, rhs in
              //sort by local peer first
              if lhs.peer.isLocal != rhs.peer.isLocal {
                   return  lhs.peer.isLocal 
              }
              //sort by active speaker
              let lhsIndex = speakers.firstIndex(of: lhs)
              let rhsIndex = speakers.firstIndex(of: rhs)
                    return lhsIndex < rhsIndex
               }
      }

**Comment by gzerad** [comment]
```
defer {
        self.speakers = speakers
    }
```
Does this trigger dataSource.reload() ? If not you need to add

p.s. you only need to set sort comparator once no need to do that on every callback.

**Comment by StackHelp** [comment]
@gzerad ok cool. I changed the code as per your suggestion

     dataSource.sortComparator = activeSpeakerSort(_:_:)

     private func activeSpeakerSort(_ lhs: HMSViewModel, _ rhs: HMSViewModel) -> Bool {
        if lhs.peer.isLocal != rhs.peer.isLocal {
            return lhs.peer.isLocal
        }
        
        if let lhsIndex = speakers.firstIndex(of: lhs),
           let rhsIndex = speakers.firstIndex(of: rhs) {
            return lhsIndex < rhsIndex
        }
        
        return false
    }


It's working right now. One more question is how to get all `HMSViewModel`? Is there any method for that to get all users currently in a room? I want to filter section models. Right now I am applying items into the section and therefore, I couldn't get all the models after the filter. How to get that?

     private func filterSections() -> [HMSSection] {
        return dataSource.sections.filter { section in
            if let activeRoomPeers = getActivePeers() {
                var matches = false
                for model in dataSource.allModels {
                    if activeRoomPeers.contains(model.peer.customerUserID ?? "") {
                        matches = true
                        break
                    }
                }
                
                let models = dataSource.allModels.filter { activeRoomPeers.contains($0.peer.customerUserID ?? "") }
                section.models = models
                return matches
            }
            return false
        }
    }

**Comment by gzerad** [comment]
You cant get all of the items post filtering. You can get complete list of peers in the room by querying hmsSDK.room?.peers

**Comment by StackHelp** [comment]
@gzerad I understand we can't get all items post-filtering then any other way we can only show required items in the room?

**Comment by gzerad** [comment]
Could you explain your use case in more detail?

**Comment by StackHelp** [comment]
yes. I have the scenario where on the selection basis I need to maintain users like I have few groups and according to groups I need to switch users. For example, I have 2 groups "G1" and "G2" and there are different users I need to display according to a selection of that group.

**Comment by StackHelp** [comment]
@gzerad  Solved that using `HMSPeer` in these 2 methods and filter peers. Thanks for your support

    private typealias DiffableDataSource = UICollectionViewDiffableDataSource<HMSSection, HMSPeer>
    private typealias Snapshot = NSDiffableDataSourceSnapshot<HMSSection, HMSPeer>
